ERROR 4: /projectnb/landsat/projects/ABOVE/CCDC/Bh16v01/out_tif/Bh16v01_1984.tif: No such file or directory
Loading .npz.npy file...
Traceback (most recent call last):
  File "/usr3/graduate/shijuan/codes/above/yatsm_v0.6_par/yatsm/mapping/plot_bgw.py", line 288, in <module>
    main()
  File "/projectnb/landsat/users/shijuan/miniconda3/envs/yatsm_v0.6_par/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/projectnb/landsat/users/shijuan/miniconda3/envs/yatsm_v0.6_par/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/projectnb/landsat/users/shijuan/miniconda3/envs/yatsm_v0.6_par/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projectnb/landsat/users/shijuan/miniconda3/envs/yatsm_v0.6_par/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr3/graduate/shijuan/codes/above/yatsm_v0.6_par/yatsm/mapping/plot_bgw.py", line 286, in main
    map_bgw(npz_file_path, img_file_path, outdir_path)
  File "/usr3/graduate/shijuan/codes/above/yatsm_v0.6_par/yatsm/mapping/plot_bgw.py", line 204, in map_bgw
    geo_info = img_file.GetGeoTransform()
AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
Finished submitting tile Bh16v01
